import { Link, useParams } from "wouter";
import { ArrowLeft, Clock3, MapPin, Search } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import Seo from "@/components/Seo";

export default function CityPage() {
  const { city = "" } = useParams<{ city: string }>();
  const label = city.split("-").map(value => value.charAt(0).toUpperCase() + value.slice(1)).join(" ");
  const { data = [], isLoading } = trpc.profiles.list.useQuery({ city: label });
  return <div className="min-h-screen bg-[#222222] text-white"><Seo title={`Acompanhantes em ${label} — Só Models`} description={`Encontre acompanhantes por cidade, categoria e disponibilidade em ${label}.`} path={`/cidade/${city}`} /><header className="border-b border-white/10"><div className="container flex items-center justify-between py-4"><Link href="/"><span className="brand-mark">Só <i>Models</i></span></Link><Link href="/"><Button variant="outline" className="border-white/15 bg-transparent text-white"><ArrowLeft className="mr-2 h-4 w-4"/>Voltar</Button></Link></div></header><main className="container py-12"><p className="eyebrow">ACOMPANHANTES NA SUA CIDADE</p><h1 className="font-display text-5xl">Acompanhantes em {label}</h1><p className="mt-4 max-w-2xl text-white/55">Explore perfis publicados, informações públicas, preferências e disponibilidade em {label}.</p>{!isLoading && !data.length ? <div className="empty-state mt-10"><div className="empty-icon"><Search className="h-7 w-7"/></div><h3>Nenhum perfil encontrado em {label}</h3><p>Quando houver perfis aprovados nesta cidade, eles aparecerão aqui.</p><Link href="/"><Button className="mt-5 bg-[#ff4764] text-[#222222]">Explorar todas as cidades</Button></Link></div> : <div className="profile-grid mt-10">{data.map(profile => <Link key={profile.id} href={`/perfil/${profile.slug}`}><Card className="profile-card"><div className="profile-image" style={profile.avatarUrl ? { backgroundImage: `url(${profile.avatarUrl})` } : undefined}><span className="profile-fallback">{profile.stageName.slice(0, 1)}</span><div className="absolute left-3 top-3 flex gap-2">{profile.isFeatured && <Badge className="bg-[#ff4764] text-[#222222]">Destaque</Badge>}{profile.isDemo && <Badge variant="outline" className="border-white/25 bg-[#222222]/70 text-white">Demo</Badge>}</div></div><CardContent className="p-4"><div className="flex items-start justify-between gap-3"><div><h2 className="text-lg font-semibold">{profile.stageName}{profile.age ? <span className="ml-2 text-sm font-normal text-white/45">{profile.age}</span> : null}</h2><p className="mt-1 text-sm text-white/50"><MapPin className="mr-1 inline h-3.5 w-3.5"/>{profile.city}</p></div></div><div className="mt-3 flex flex-wrap gap-1.5">{profile.categories.slice(0, 3).map((tag: string) => <Badge key={tag} variant="outline" className="border-white/15 text-white/60">{tag}</Badge>)}</div><p className={`mt-4 text-xs uppercase tracking-[.12em] ${profile.isAvailableNow ? "text-[#ff9a8e]" : "text-white/40"}`}><Clock3 className="mr-1 inline h-3.5 w-3.5"/>{profile.isAvailableNow ? "Disponível agora" : profile.availabilityLabel || "Consulte disponibilidade"}</p></CardContent></Card></Link>)}</div>}</main></div>;
}
